export const AUTH_SET_LOGGED_IN = "AUTH_SET_LOGGED_IN";
export const AUTH_SET_LOGGED_OUT = "AUTH_SET_LOGGED_OUT";
export const LOAD_FAVORITES = "LOAD_FAVORITES";
export const ADD_FAVORITE = "ADD_FAVORITE";
export const REMOVE_FAVORITE = "REMOVE_FAVORITE";